'use strict'

const STRaction     = 'action'
const STRassociate  = 'associate'
const STRbody       = 'body'
const STRbook       = 'book'
const STRbrin       = 'brin'
const STRbutton     = 'button'
const STRcheckbox   = 'checkbox'
const STRclick      = 'click'
const STRdata_type  = 'data-type'
const STRdata_id    = 'data-id'
const STRdialog     = 'dialog'
const STRdocument   = 'document'
const STRdyna       = 'dyna'
const STRevent      = 'event'
const STRfooter     = 'footer'
const STRfull       = 'full'
const STRfunction   = 'function'
const STRheader     = 'header'
const STRhidden     = 'hidden'
const STRimage      = 'image'
const STRidee       = 'idee'
const STRinfo       = 'info'
const STRj          = 'j'
const STRk          = 'k'
const STRl          = 'l'
const STRnumber     = 'number'
const STRnote       = 'note'
const STRobject     = 'object'
const STRobserved   = 'observed'
const STROBSERVED   = 'OBSERVED'
const OK            = 'OK'
const STRpersonnage = 'personnage'
const STRproc       = 'proc'
const STRqrd        = 'qrd'
const STRstring     = 'string'
const STRselect     = 'select'
const STRscene      = 'scene'
const STRshort      = 'short'
const STRsmall      = 'small'
const STRstt        = 'stt'
const STRtext       = 'text'
const STRtextarea   = 'textarea'
const STRtime       = 'time'
const STRvisible    = 'visible'
const STRundefined  = 'undefined'

const NONE = 'undefined'

const HTML = 'html'

const EBOOK_CONVERT_CMD = '/Applications/calibre.app/Contents/console.app/Contents/MacOS/ebook-convert'

const REG_DATE = new RegExp("(?<jour>[0-9]?[0-9])\\/(?<mois>[0-9]?[0-9])\\/(?<annee>[0-9]{4,4})")

const A       = 'A'
const LI      = 'LI'
const DIV     = 'DIV'
const H2      = 'H2'
const H3      = 'H3'
const H4      = 'H4'
const IMG     = 'IMG'
const SPAN    = 'SPAN'
const FORM    = 'FORM'
const BUTTON  = 'BUTTON'
const INPUT   = 'INPUT'
const SELECT  = 'SELECT'
const SECTION = 'SECTION'
const TEXTAREA= 'TEXTAREA'
const OPTION  = 'OPTION'
const LABEL   = 'LABEL'


const ReaderFWindowName = 'Reader'
const BtnsEventFWindowName = 'NewEventsButtons'
